language: python
sudo: false

env:
  global:
    - PIP_DEPS="pytest coveralls coverage pytest-cov flake8"

python:
  - '2.7'
  - '3.6'
    
install:
- travis_retry pip install $PIP_DEPS
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
- flake8 --ignore N802,N806,E501,E741,F841,F821 `find . -name \*.py | grep -v setup.py | grep -v version.py | grep -v __init__.py | grep -v /dm3_lib/`

after_success:
- coveralls
- coverage report

notifications:
    slack: gingerlab:tFpXzHAuqsR3X17wUKaY3wMh
