language: python
sudo: false

env:
  global:
    - PIP_DEPS="pytest coveralls pytest-cov flake8"

python:
  - '2.7'
  - '3.6'

before_install:
    - pip install --upgrade pip
    - pip install pep8
    - pip install autopep8
    
install:
- travis_retry pip install $PIP_DEPS
- travis_retry pip install -r requirements.txt
#- travis_retry pip install -e .

script:
- flake8 --ignore N802,N806,E501,E741,F841 `find . -name \*.py | grep -v setup.py | grep -v version.py | grep -v __init__.py | grep -v /dm3_lib/`

after_success:
- coveralls

notifications:
    slack: gingerlab:tFpXzHAuqsR3X17wUKaY3wMh
