language: python
sudo: false

env:
  global:
    - PIP_DEPS="pytest coveralls pytest-cov flake8"
    
python:
-'3.6.4'

install:
- travis_retry pip install $PIP_DEPS
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .
  
after_success:
- coveralls

notifications:
    slack: gingerlab:tFpXzHAuqsR3X17wUKaY3wMh
